# .github/workflows/update-latest-tag.yml
name: Update 'latest' Git Tag

on:
  push:
    tags:
      - 'v*'  # 每当推送 v1.2.5 这类标签时触发

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录和标签
      - name: Force update 'latest' tag
        run: |
          git tag -f latest
          git push -f origin latest
